hooks: fix putting Chrome into favorite-apps
In the past, we applied our Endless-specific favorite apps by patching
the schema. Since https://phabricator.endlessm.com/T25835 we moved to
using vendor overrides, as is right and proper. However, this hook to
replace Chromium with Chrome on free images was implemented by scraping
the schema, so in an attempt to replace Chromium with Chrome we actually
undid our vendor customization and ended up with Evolution, Rhythmbox,
Shotwell, Nautilus, App Center on the taskbar – and no browser!

Fix this by scraping the override file instead, and add a check that the
string being modified actually contains "chromium-browser", which would
have caught this oversight.

https://phabricator.endlessm.com/T28610

diff --git a/hooks/image/50-google-chrome b/hooks/image/50-google-chrome
--- a/hooks/image/50-google-chrome
+++ b/hooks/image/50-google-chrome
@@ -29,10 +29,9 @@ done
 # Override the gsetting for favorite apps so that
 # Chrome is on the taskbar by default rather than Chromium
 
-# Parse the gschema XML file for lines such as the following:
+# Parse the gsettings override file, finding a line like this:
 #
-#     <key name="favorite-apps" type="as">
-#       <default>[ 'org.gnome.Software.desktop', 'chromium-browser.desktop', 'org.gnome.Nautilus.desktop' ]</default>
+# favorite-apps=['org.gnome.Software.desktop', 'chromium-browser.desktop', 'org.gnome.Nautilus.desktop']
 #
 # And then write a settings file such as the following that
 # will be picked up by the 61-dconf-compile.chroot hook:
@@ -40,16 +39,18 @@ done
 # [org/gnome/shell]
 # favorite-apps=['org.gnome.Software.desktop', 'chromium-browser.desktop', 'org.gnome.Nautilus.desktop']
 
-GSCHEMA_XML="${OSTREE_DEPLOYMENT}"/usr/share/glib-2.0/schemas/org.gnome.shell.gschema.xml
+GSCHEMA_OVERRIDES="${OSTREE_DEPLOYMENT}"/usr/share/glib-2.0/schemas/50_eos-theme.gschema.override
 SETTINGS_DIR="${OSTREE_DEPLOYMENT}"/tmp/dconf-overrides
 TASKBAR_SETTINGS="${SETTINGS_DIR}"/taskbar-settings
 
-apps=`grep -A1 'name="favorite-apps"' "${GSCHEMA_XML}" | tail -1`
-apps=${apps#*[ }
-apps=${apps% ]*}
+apps=$(grep '^favorite-apps=' "${GSCHEMA_OVERRIDES}")
+if [[ "$apps" != *chromium-browser* ]]; then
+    echo "ERROR: $apps doesn't mention chromium-browser"
+    exit 1
+fi
 apps=${apps/chromium-browser/google-chrome}
 mkdir -p "${SETTINGS_DIR}"
 cat <<EOF > "${TASKBAR_SETTINGS}"
 [org/gnome/shell]
-favorite-apps=[${apps}]
+${apps}
 EOF
