Enable different plugins for Endless Key
The Endless Key app needs a different set of plugins than traditional
Kolibri.

https://github.com/endlessm/eos-image-builder/issues/117

diff --git a/hooks/image/60-kolibri-content b/hooks/image/60-kolibri-content
--- a/hooks/image/60-kolibri-content
+++ b/hooks/image/60-kolibri-content
@@ -74,14 +74,43 @@ prepare_kolibri_env()
   source ${venv_dir}/bin/activate
 
   pip install kolibri==${EIB_KOLIBRI_APP_VERSION}
-  pip install kolibri-app-desktop-xdg-plugin==${EIB_KOLIBRI_APP_DESKTOP_XDG_PLUGIN_VERSION}
-  pip install kolibri-desktop-auth-plugin==${EIB_KOLIBRI_DESKTOP_AUTH_PLUGIN_VERSION}
 
   export KOLIBRI_HOME="${KOLIBRI_CONTENT_DIR}"
 
-  kolibri plugin enable kolibri.plugins.app
-  kolibri plugin enable kolibri_app_desktop_xdg_plugin
-  kolibri plugin enable kolibri_desktop_auth_plugin
+  if [ ${app_name} == "kolibri" ]; then
+    PLUGINS_DISABLE=()
+    PLUGINS_ENABLE=(
+      "kolibri.plugins.app"
+      "kolibri_app_desktop_xdg_plugin"
+      "kolibri_desktop_auth_plugin"
+    )
+    pip install kolibri-app-desktop-xdg-plugin==${EIB_KOLIBRI_APP_DESKTOP_XDG_PLUGIN_VERSION}
+    pip install kolibri-desktop-auth-plugin==${EIB_KOLIBRI_DESKTOP_AUTH_PLUGIN_VERSION}
+  elif [ ${app_name} == "endless-key" ]; then
+    PLUGINS_DISABLE=(
+      "kolibri.plugins.default_theme"
+      "kolibri.plugins.learn"
+    )
+    PLUGINS_ENABLE=(
+      "kolibri.plugins.app"
+      "kolibri_endless_key_theme"
+      # FIXME: enabling kolibri-explore-plugin fails because we are using a
+      #        kolibri version that is too old.
+      #"kolibri_explore_plugin"
+      "kolibri_zim_plugin"
+    )
+    pip install kolibri_endless_key_theme
+    pip install kolibri_explore_plugin
+    pip install kolibri_zim_plugin
+  else
+    exit 1
+  fi
+  for plugin in "${PLUGINS_DISABLE[@]}"; do
+    kolibri plugin disable ${plugin}
+  done
+  for plugin in "${PLUGINS_ENABLE[@]}"; do
+    kolibri plugin enable ${plugin}
+  done
 
   if [ ${app_name} == "kolibri" ]; then
     INSTALL_CHANNELS=("${EIB_KOLIBRI_INSTALL_CHANNELS[@]}")
