applist: take size to save as parameter, not total budget
It's hard to determine in general how much space is available for apps,
but it's very easy to determine how much space must be saved by just
trying the build and reading the error message. (It's even easier if we
subtract one number from the other in the error message.)

diff --git a/helpers/create-iso b/helpers/create-iso
--- a/helpers/create-iso
+++ b/helpers/create-iso
@@ -145,7 +145,9 @@ AUTORUN_INF
   if [ "${EIB_ISO_MAX_SIZE}" ]; then
     local iso_size=$(stat --printf='%s' "${iso}")
     if [ "${iso_size}" -gt "${EIB_ISO_MAX_SIZE}" ]; then
-      echo "ERROR: ${iso} is ${iso_size} bytes; limit is ${EIB_ISO_MAX_SIZE} bytes" >&2
+      local excess=$(( "${EIB_ISO_MAX_SIZE}" - "${iso_size}" ))
+      echo "ERROR: ${iso} is ${iso_size} bytes, " \
+        "${excess} bytes above limit of ${EIB_ISO_MAX_SIZE} bytes" >&2
       return 1
     fi
   fi
