helpers: log actual size when disk1 exceeds limit
Previously, the error message was of the form:

    ERROR: en disk1 image exceeds 14606258176

I had to manually re-evaluate the expressions from the build log to know
how much I had to shave off (a lot!). Let's include both numbers here.

https://phabricator.endlessm.com/T28336#769688

diff --git a/helpers/split-image b/helpers/split-image
--- a/helpers/split-image
+++ b/helpers/split-image
@@ -63,8 +63,8 @@ shrink_disk1_image() {
   disk1_max_img_size=$(python -c "print int(${disk1_size} * 0.98)")
   ((disk1_max_img_size -= 1 * 2**30))
   if ((new_disk1_img_size > disk1_max_img_size)); then
-    echo "ERROR: ${EIB_PERSONALITY} disk1 image exceeds" \
-         "${disk1_max_img_size}" >&2
+    echo "ERROR: ${EIB_PERSONALITY} disk1 image size ${new_disk1_img_size} " \
+         "exceeds ${disk1_max_img_size}" >&2
     return 1
   fi
 
