buildscript: Ensure all needed variables set
Now that the build depends on environment variables to be set by
run-build, we should check that they're actually set. This doesn't check
every possible variable, but rather the ones that were previously set in
eib.sh.

diff --git a/buildscript b/buildscript
--- a/buildscript
+++ b/buildscript
@@ -8,6 +8,17 @@ stage_error() {
 }
 trap stage_error ERR
 
+# Ensure all needed settings are available from the environment.
+for var in EIB_BASELIB EIB_SCRATCH EIB_OSTREE_CHECKOUT EIB_OSTREE \
+  EIB_DATA EIB_HELPERS EIB_OUT_ROOT EIB_CACHEDIR EIB_TMPDIR \
+  EIB_OSTREE_TMPDIR EIB_CONTENT EIB_APPS_CONTENT
+do
+  if [ ! -v $var ]; then
+    echo "error: required variable $var not set" >&2
+    exit 1
+  fi
+done
+
 # Read system config overrides
 [[ -e "${EIB_SYSCONF}"/config ]] && . "${EIB_SYSCONF}"/config
 
