eos-image-builder: Add locking
Prevent multiple instances from running at the same time.

diff --git a/eos-image-builder b/eos-image-builder
--- a/eos-image-builder
+++ b/eos-image-builder
@@ -1,116 +1,11 @@
 #!/bin/bash
+MYDIR=$(dirname $(readlink -f $0))
 
-## image-builder - Image System Build Scripts
-## Copyright (C) 2012 Hector Oron <hector.oron@collabora.co.uk>
-##
-## image-builder comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
-## This is free software, and you are welcome to redistribute it
-## under certain conditions; see COPYING for details.
+(
+	if ! flock -n 9; then
+		echo "ERROR: instance already running" >&2
+		exit 1
+	fi
 
-# (C) 2012 Hector Oron <hector.oron@collabora.co.uk>
-set -x
-timestamp=`date "+%y%m%d-%H%M%S"`
-builddir="/scratch/tmp/"
-logdir="${builddir}"/logs
-SUITE=dev
-export MYDIR=$(dirname $(readlink -f $0))
-export CB_BASE=$builddir/cb_base
-
-processJob(){
-local _product="${1}"
-local _dist="${2}"
-local _platform="${3}"
-local _arch="${4}"
-local _device="${5}"
-local _timestamp="${6}"
-local _builddir="${7}"
-
-echo "I: trigger configuration"
-
-rm -rf ${builddir}/${_builddir}
-mkdir -p ${builddir}/${_builddir}
-
-cd ${builddir}/${_builddir}
-
-_compo="core endless extra"
-case ${_arch} in
-armhf)
-  _image_size="3584M"
-;;
-*)
-  _image_size="7.5G"
-;;
-esac
-
-  _image_format="img"
-  if [ x"${_arch}" = xi386 ] ; then
-    _image_format="vdi img"
-  fi
-
-  hwpack_tmpl="${_product}-${_arch}-${_device}.yaml.in"
-  hwpack_conf="${_dist}-${_arch}-${_device}-${_product}.yaml"
-  repo_url="http://obs-master.endlessm-sf.com:82/shared/${_product}/"
-  sed -e "s/@DIST@/${_dist}/g" -e "s/@PRODUCT@/${_product}/g" \
-    -e "s/@COMPONENTS@/${_compo}/g" -e "s,@REPO@,${repo_url},g" \
-    $MYDIR/customization/hwpack/${hwpack_tmpl} > $CB_BASE/customization/hwpack/${hwpack_conf}
-
-  cb config -s "${_dist}" \
-	-d "${_product}" \
-	-a "${_arch}" \
-	--components "${_compo}" \
-	-c "${_device}" \
-	-f "${hwpack_conf}" \
-	-p "core" \
-	-fmt "ext4" \
-	-it "${_image_format}" \
-	-i "${_image_size}" \
-	-b "${builddir}/${_builddir}/" \
-	--shared-dir "${builddir}/" \
-	-m "${repo_url}" \
-	-rmirror "${repo_url}" \
-	--postprocess \
-	-t $timestamp 2>&1
-
-cd ${builddir}/"${_builddir}"/
-cb build | tee ${logdir}/build_"${_dist}"-"${_platform}"-"${_arch}"-"${_device}"_"${_timestamp}".txt 2>&1 &
-
-}
-
-# Archive old logs
-mkdir -p "$logdir"
-cd "$logdir"
-mkdir -p archived
-find . -maxdepth 1 -name '*.txt' -exec mv -t archived '{}' +
-cd archived
-find . -maxdepth 1 -name '*.txt' -exec gzip -9 '{}' +
-cd -
-
-# Clean up
-
-rm -rf "${builddir}"/ospack-build/
-rm -rf "${builddir}"/hwpack-build/
-rm -rf "${builddir}"/image-build/
-rm -rf $CB_BASE
-
-# Set up input for cb
-mkdir -p $CB_BASE/customization/hwpack
-ln -s $MYDIR/functions $CB_BASE
-ln -snf $MYDIR/customization/eos $CB_BASE/customization/$SUITE
-
-# Endless
-processJob eos $SUITE core i386 i386 ${timestamp} "end/i386-core"
-processJob eos $SUITE core armhf odroidx2 ${timestamp} "end/odroidx2-core"
-wait
-processJob eos $SUITE core armhf odroidu2 ${timestamp} "end/odroidu2-core"
-wait
-
-# -- Publish images
-webdir=/srv/images/www/dev/${timestamp}
-mkdir -p $webdir
-mv ${builddir}/image-build/* ${webdir}
-
-mkdir -p ${webdir}/logs
-ln ${logdir}/*.txt ${webdir}/logs
-
-# Purge old builds
-find ${webdir}/.. -maxdepth 1 -type d -ctime +7 -exec rm -rf '{}' \;
+	$MYDIR/build.sh $@
+) 9>/var/tmp/eos-image-builder.lock
