Allow specifying a maximum size for the full image
We are defining a new personality, lite_en, destined for systems with a
single 32GB disk. This personality's size should be capped at 24GB,
allowing headroom for user data, new apps, and updates for apps and the
OS.

To enforce this, allow the configuration to specify a maximum size for
the image and fail if it would be exceeded. This is similar to the
existing [image] disk1_size, [image] disk2_size and [iso] max_size
fields.

https://phabricator.endlessm.com/T26787

diff --git a/stages/eib_image b/stages/eib_image
--- a/stages/eib_image
+++ b/stages/eib_image
@@ -184,6 +184,12 @@ create_image() {
   (( extra_size < min_extra_size )) && extra_size=${min_extra_size}
   (( img_size += extra_size ))
   (( img_size -= img_size % 512 ))
+
+  if [[ "${EIB_IMAGE_MAX_SIZE}" ]] && (( img_size > EIB_IMAGE_MAX_SIZE )); then
+    echo "ERROR: $1 image size ${img_size} exceeds ${EIB_IMAGE_MAX_SIZE}" >&2
+    return 1
+  fi
+
   echo "Creating $1 image with size ${img_size}"
 
   local img="${EIB_TMPDIR}/${EIB_OUTVERSION}.img"
